- hosts: os_Ubuntu
  tasks:
    # Slurm installation
    - name: Install Slurm
      apt:
        name: '{{ slurm_package_version }}'
        state: present
    - name: Install Munge
      apt:
        name: munge
        state: present

    - name: Copy munge.key
      copy:
        src: munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'